[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
jiff = { workspace = true }
rust_decimal = { workspace = true, features = ["serde-with-str"] }
chrono = { workspace = true, features = ["serde"] }
